in="./excel"
out="./output"
info="./output/info.json"
json="./output/data/"
ignore=""
branch=""


GOPackage="configs"
CSPackage="Cosnet.configs"


ProtoHeader="./base.proto"
EnableGlobalDummyName=false
NamedDummyInHeader=true

[enum.BaseEnum]
src="base"
index=[0,1,2,3]