in="./excel"
out="./output"
info="./output/info.json"
json="./output/data/"
ignore=""
branch=""


GOPackage="configs"
CSPackage="Cosnet.configs"
JsonCompact=false

#ProtoHeader="./base.proto"
EnableGlobalDummyName=true
NamedDummyInHeader=false

[enum.BaseEnum]
src="base"
index=[0,1,2,3]