// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.22.1
// source: message.proto

package gameData

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//全局对象......
type IdInt32NumInt32PerInt32 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Num int32 `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	Per int32 `protobuf:"varint,3,opt,name=per,proto3" json:"per,omitempty"`
}

func (x *IdInt32NumInt32PerInt32) Reset() {
	*x = IdInt32NumInt32PerInt32{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdInt32NumInt32PerInt32) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdInt32NumInt32PerInt32) ProtoMessage() {}

func (x *IdInt32NumInt32PerInt32) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdInt32NumInt32PerInt32.ProtoReflect.Descriptor instead.
func (*IdInt32NumInt32PerInt32) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *IdInt32NumInt32PerInt32) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *IdInt32NumInt32PerInt32) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *IdInt32NumInt32PerInt32) GetPer() int32 {
	if x != nil {
		return x.Per
	}
	return 0
}

type IdInt32NumInt32 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Num int32 `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *IdInt32NumInt32) Reset() {
	*x = IdInt32NumInt32{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdInt32NumInt32) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdInt32NumInt32) ProtoMessage() {}

func (x *IdInt32NumInt32) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdInt32NumInt32.ProtoReflect.Descriptor instead.
func (*IdInt32NumInt32) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *IdInt32NumInt32) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *IdInt32NumInt32) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

//数据对象......
type Activity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int32                    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TType  string                   `protobuf:"bytes,2,opt,name=TType,proto3" json:"TType,omitempty"`
	Arr    []int32                  `protobuf:"varint,3,rep,packed,name=Arr,proto3" json:"Arr,omitempty"`
	Obj    *IdInt32NumInt32PerInt32 `protobuf:"bytes,6,opt,name=Obj,proto3" json:"Obj,omitempty"`
	ArrObj []*IdInt32NumInt32       `protobuf:"bytes,9,rep,name=ArrObj,proto3" json:"ArrObj,omitempty"`
}

func (x *Activity) Reset() {
	*x = Activity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Activity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Activity) ProtoMessage() {}

func (x *Activity) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Activity.ProtoReflect.Descriptor instead.
func (*Activity) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2}
}

func (x *Activity) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Activity) GetTType() string {
	if x != nil {
		return x.TType
	}
	return ""
}

func (x *Activity) GetArr() []int32 {
	if x != nil {
		return x.Arr
	}
	return nil
}

func (x *Activity) GetObj() *IdInt32NumInt32PerInt32 {
	if x != nil {
		return x.Obj
	}
	return nil
}

func (x *Activity) GetArrObj() []*IdInt32NumInt32 {
	if x != nil {
		return x.ArrObj
	}
	return nil
}

var File_message_proto protoreflect.FileDescriptor

var file_message_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x4d, 0x0a, 0x17, 0x49, 0x64, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x4e, 0x75, 0x6d, 0x49, 0x6e, 0x74,
	0x33, 0x32, 0x50, 0x65, 0x72, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75,
	0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12, 0x10, 0x0a, 0x03,
	0x70, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x70, 0x65, 0x72, 0x22, 0x33,
	0x0a, 0x0f, 0x49, 0x64, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x4e, 0x75, 0x6d, 0x49, 0x6e, 0x74, 0x33,
	0x32, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x6e, 0x75, 0x6d, 0x22, 0x98, 0x01, 0x0a, 0x08, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x54, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x54, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x41, 0x72, 0x72, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x05, 0x52, 0x03, 0x41, 0x72, 0x72, 0x12, 0x2a, 0x0a, 0x03, 0x4f, 0x62, 0x6a, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x49, 0x64, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x4e,
	0x75, 0x6d, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x50, 0x65, 0x72, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x52,
	0x03, 0x4f, 0x62, 0x6a, 0x12, 0x28, 0x0a, 0x06, 0x41, 0x72, 0x72, 0x4f, 0x62, 0x6a, 0x18, 0x09,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x49, 0x64, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x4e, 0x75,
	0x6d, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x52, 0x06, 0x41, 0x72, 0x72, 0x4f, 0x62, 0x6a, 0x42, 0x0d,
	0x5a, 0x0b, 0x2e, 0x2f, 0x3b, 0x67, 0x61, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData = file_message_proto_rawDesc
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_proto_rawDescData)
	})
	return file_message_proto_rawDescData
}

var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_message_proto_goTypes = []interface{}{
	(*IdInt32NumInt32PerInt32)(nil), // 0: IdInt32NumInt32PerInt32
	(*IdInt32NumInt32)(nil),         // 1: IdInt32NumInt32
	(*Activity)(nil),                // 2: activity
}
var file_message_proto_depIdxs = []int32{
	0, // 0: activity.Obj:type_name -> IdInt32NumInt32PerInt32
	1, // 1: activity.ArrObj:type_name -> IdInt32NumInt32
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdInt32NumInt32PerInt32); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdInt32NumInt32); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Activity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_rawDesc = nil
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
